In [3]:
pip install pandas numpy matplotlib

Collecting pandas
  Downloading pandas-3.0.1-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Using cached numpy-2.4.2-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.8-cp314-cp314-win_amd64.whl.metadata (52 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\venkatesh\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.61.1-cp314-cp314-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.9-cp314-cp314-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\venkatesh\appdata\roaming\python\python314\site-packages (from matplotlib) (26.0)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-12.1.1-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in c:\users\venkatesh\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.9 MB 11.5 MB/s eta 0:00:01
   --------------- ------------------------ 3.9/9.9 MB 11.2 MB/s eta 0:00:01
   ------------------------- -------------- 6.3/9.9 MB 11.1 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 11.0 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 10.1 MB/s  0:00:01
Using cached numpy-2.4.2-cp314-cp314-win_amd64.whl (12.4 MB)
Using cached matplotlib-3.10.8-cp314-cp314-win_amd64.whl (8.3 MB)
Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.61.1-cp314-cp314-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.4.9-cp314-cp314-win_amd64.whl (75 kB)
Using cached pillow-12.1.1-cp314-cp314-win_amd64.whl (7.2 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pyparsing, pillow, numpy, kiwisolver, fonttools, cycler, pandas, contourpy, matplotlib

   ----------------------------------------  0/10 [tzdata]
   ----------------------------------------  0/10 [tzdata]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   -------- -------------------------------  2/10 [pillow]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   ------------ ---------------------------  3/10 [numpy]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   -------------------- -------------------  5/10 [fonttools]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ---------------------------- -----------  7/10 [pandas]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ------------------------------------ ---  9/10 [matplotlib]
   ---------------------------------------- 10/10 [matplotlib]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.61.1 kiwisolver-1.4.9 matplotlib-3.10.8 numpy-2.4.2 pandas-3.0.1 pillow-12.1.1 pyparsing-3.3.2 tzdata-2025.3
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\Venkatesh\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\Users\Venkatesh\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
pip install seaborn

Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\venkatesh\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from seaborn) (2.4.2)
Requirement already satisfied: pandas>=1.2 in c:\users\venkatesh\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from seaborn) (3.0.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\venkatesh\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\venkatesh\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\venkatesh\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\venkatesh\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\venkatesh\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\venkatesh\appdata\roaming\python\python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\venkatesh\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\venkatesh\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\venkatesh\appdata\roaming\python\python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\venkatesh\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\venkatesh\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mp
import seaborn as sns

In [9]:
df = pd.read_csv("../data/House Prices.csv")

In [10]:
df.head()

,ID,Date,Price,Bedrooms,Bathrooms,Sqft_living,Sqft_lot,Floors,Waterfront,View,...,Grade,Sqft_above,Sqft_basement,Yr_built,Yr_renovated,zipcode,Lat,Long,Sqft_living15,Sqft_lot15
0,1,20140916T000000,280000.0,6,3.00,2400,9373,2.0,0,0,...,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316
1,2,20150422T000000,300000.0,6,3.00,2400,9373,2.0,0,0,...,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316
2,3,20140508T000000,647500.0,4,1.75,2060,26036,1.0,0,0,...,8,1160,900,1947,0,98166,47.4444,-122.351,2590,21891
3,4,20140811T000000,400000.0,3,1.00,1460,43000,1.0,0,0,...,7,1460,0,1952,0,98166,47.4434,-122.347,2250,20023
4,5,20150401T000000,235000.0,3,1.00,1430,7599,1.5,0,0,...,6,1010,420,1930,0,98168,47.4783,-122.265,1290,10320

In [11]:
df.shape

(21613, 21)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             21613 non-null  int64
 1   Date           21613 non-null  str
 2   Price          21613 non-null  float64
 3   Bedrooms       21613 non-null  int64
 4   Bathrooms      21613 non-null  float64
 5   Sqft_living    21613 non-null  int64
 6   Sqft_lot       21613 non-null  int64
 7   Floors         21613 non-null  float64
 8   Waterfront     21613 non-null  int64
 9   View           21613 non-null  int64
 10  Condition      21613 non-null  int64
 11  Grade          21613 non-null  int64
 12  Sqft_above     21613 non-null  int64
 13  Sqft_basement  21613 non-null  int64
 14  Yr_built       21613 non-null  int64
 15  Yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  Lat            21613 non-null  float64
 18  Long           21613 non-null  float64
 19  Sqft_living15  21613 non-null  int64
 20  Sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), str(1)
memory usage: 3.5 MB

In [14]:
df.describe()

,ID,Price,Bedrooms,Bathrooms,Sqft_living,Sqft_lot,Floors,Waterfront,View,Condition,Grade,Sqft_above,Sqft_basement,Yr_built,Yr_renovated,zipcode,Lat,Long,Sqft_living15,Sqft_lot15
count,21613.00000,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,10807.00000,5.401822e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,6239.28002,3.673622e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.00000,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,5404.00000,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,10807.00000,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,16210.00000,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,21613.00000,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [15]:
df.isnull().sum()

ID               0
Date             0
Price            0
Bedrooms         0
Bathrooms        0
Sqft_living      0
Sqft_lot         0
Floors           0
Waterfront       0
View             0
Condition        0
Grade            0
Sqft_above       0
Sqft_basement    0
Yr_built         0
Yr_renovated     0
zipcode          0
Lat              0
Long             0
Sqft_living15    0
Sqft_lot15       0
dtype: int64

In [17]:
df.head()

,ID,Date,Price,Bedrooms,Bathrooms,Sqft_living,Sqft_lot,Floors,Waterfront,View,...,Grade,Sqft_above,Sqft_basement,Yr_built,Yr_renovated,zipcode,Lat,Long,Sqft_living15,Sqft_lot15
0,1,20140916T000000,280000.0,6,3.00,2400,9373,2.0,0,0,...,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316
1,2,20150422T000000,300000.0,6,3.00,2400,9373,2.0,0,0,...,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316
2,3,20140508T000000,647500.0,4,1.75,2060,26036,1.0,0,0,...,8,1160,900,1947,0,98166,47.4444,-122.351,2590,21891
3,4,20140811T000000,400000.0,3,1.00,1460,43000,1.0,0,0,...,7,1460,0,1952,0,98166,47.4434,-122.347,2250,20023
4,5,20150401T000000,235000.0,3,1.00,1430,7599,1.5,0,0,...,6,1010,420,1930,0,98168,47.4783,-122.265,1290,10320

In [18]:
df = df.drop(columns=["ID", "Date", ])

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Price          21613 non-null  float64
 1   Bedrooms       21613 non-null  int64
 2   Bathrooms      21613 non-null  float64
 3   Sqft_living    21613 non-null  int64
 4   Sqft_lot       21613 non-null  int64
 5   Floors         21613 non-null  float64
 6   Waterfront     21613 non-null  int64
 7   View           21613 non-null  int64
 8   Condition      21613 non-null  int64
 9   Grade          21613 non-null  int64
 10  Sqft_above     21613 non-null  int64
 11  Sqft_basement  21613 non-null  int64
 12  Yr_built       21613 non-null  int64
 13  Yr_renovated   21613 non-null  int64
 14  zipcode        21613 non-null  int64
 15  Lat            21613 non-null  float64
 16  Long           21613 non-null  float64
 17  Sqft_living15  21613 non-null  int64
 18  Sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(14)
memory usage: 3.1 MB

In [21]:
X = df.drop("Price", axis=1)
y = df["Price"]

In [22]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Bedrooms       21613 non-null  int64
 1   Bathrooms      21613 non-null  float64
 2   Sqft_living    21613 non-null  int64
 3   Sqft_lot       21613 non-null  int64
 4   Floors         21613 non-null  float64
 5   Waterfront     21613 non-null  int64
 6   View           21613 non-null  int64
 7   Condition      21613 non-null  int64
 8   Grade          21613 non-null  int64
 9   Sqft_above     21613 non-null  int64
 10  Sqft_basement  21613 non-null  int64
 11  Yr_built       21613 non-null  int64
 12  Yr_renovated   21613 non-null  int64
 13  zipcode        21613 non-null  int64
 14  Lat            21613 non-null  float64
 15  Long           21613 non-null  float64
 16  Sqft_living15  21613 non-null  int64
 17  Sqft_lot15     21613 non-null  int64
dtypes: float64(4), int64(14)
memory usage: 3.0 MB

In [23]:
y.info()

<class 'pandas.Series'>
RangeIndex: 21613 entries, 0 to 21612
Series name: Price
Non-Null Count  Dtype
--------------  -----
21613 non-null  float64
dtypes: float64(1)
memory usage: 169.0 KB

In [24]:
X

,Bedrooms,Bathrooms,Sqft_living,Sqft_lot,Floors,Waterfront,View,Condition,Grade,Sqft_above,Sqft_basement,Yr_built,Yr_renovated,zipcode,Lat,Long,Sqft_living15,Sqft_lot15
0,6,3.00,2400,9373,2.0,0,0,3,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316
1,6,3.00,2400,9373,2.0,0,0,3,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316
2,4,1.75,2060,26036,1.0,0,0,4,8,1160,900,1947,0,98166,47.4444,-122.351,2590,21891
3,3,1.00,1460,43000,1.0,0,0,3,7,1460,0,1952,0,98166,47.4434,-122.347,2250,20023
4,3,1.00,1430,7599,1.5,0,0,4,6,1010,420,1930,0,98168,47.4783,-122.265,1290,10320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,5,2.00,1600,4168,1.5,0,0,3,7,1600,0,1927,0,98126,47.5297,-122.381,1190,4168
21609,2,1.00,1040,7372,1.0,0,0,5,7,840,200,1939,0,98126,47.5285,-122.378,1930,5150
21610,3,1.00,1100,4128,1.0,0,0,4,7,720,380,1942,0,98126,47.5296,-122.379,1510,4538
21611,2,1.75,1410,1005,1.5,0,0,3,9,900,510,2011,0,98027,47.5446,-122.018,1440,1188
21612,3,1.00,1320,8100,1.0,0,0,3,6,880,440,1943,0,98166,47.4697,-122.351,1000,8100

In [25]:
y

0        280000.0
1        300000.0
2        647500.0
3        400000.0
4        235000.0
           ...
21608    365000.0
21609    380000.0
21610    339000.0
21611    399900.0
21612    268950.0
Name: Price, Length: 21613, dtype: float64

In [ ]:
pip install scikit-learn

In [29]:
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=40, test_size=0.2)

In [30]:
from sklearn.linear_model import LinearRegression

model  = LinearRegression()

In [ ]:
from sklearn.linear_model import LinearRegression, 

model  = LinearRegression()

In [31]:
model.fit(X_train, y_train)

LinearRegression()

In [37]:
y_test

21568    690000.0
3040     329000.0
198      630000.0
16456    240000.0
19502    335000.0
           ...
12385    780000.0
18099    385000.0
9347     277000.0
18718    855000.0
8642     250000.0
Name: Price, Length: 4323, dtype: float64

In [33]:
y_pred = model.predict(X_test)

In [38]:
y_pred_train = model.predict(X_train)

In [39]:
y_pred_train

array([501313.78317328, 593019.26558941, 771793.66659354, ...,
       515785.42291875, 327561.05411857, 357487.86833063], shape=(17290,))

In [36]:
y_pred[0]

np.float64(662587.8610757198)

In [49]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error

MSE = mean_squared_error(y_train, y_pred_train)
R2score = r2_score(y_train, y_pred_train)
MAE = mean_absolute_error(y_train, y_pred_train)
RMSE = root_mean_squared_error(y_train, y_pred_train)

In [50]:
MSE

38889274275.04868

In [51]:
MAE

124009.32253995807

In [52]:
R2score

0.6982005815069156

In [53]:
RMSE

197203.63656649104

In [55]:
y_pred_test = model.predict(X_test)

In [57]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error

MSE = mean_squared_error(y_test, y_pred_test)
R2score = r2_score(y_test, y_pred_test)
MAE = mean_absolute_error(y_test, y_pred_test)
RMSE = root_mean_squared_error(y_test, y_pred_test)

print("MSE:", MSE)
print("R2score:", R2score)
print("MAE:", MAE)
print("RMSE:", RMSE)

MSE: 47308169296.91754
R2score: 0.7027109823319095
MAE: 127582.2634367129
RMSE: 217504.41213207043

In [ ]:
C:\Users\Venkatesh\Downloads\Creative_Workstation\ML_Projects\Houseprediction_Project\notebooks

In [ ]:
notebooks