In [214]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [215]:
train = pd.read_csv("../data/predtrain.csv")
test = pd.read_csv("../data/predtest.csv")

In [216]:
train.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [217]:
test.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,594194,Female,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,115.55,8061.50
1,594195,Female,0,Yes,No,71,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),19.80,1336.50
2,594196,Male,0,No,No,12,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),55.55,633.55
3,594197,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),84.10,6457.15
4,594198,Female,0,No,No,15,Yes,No,Fiber optic,Yes,No,No,No,Yes,Yes,Month-to-month,No,Electronic check,90.35,1233.65

In [218]:
train["Churn"].value_counts()

Churn
No     460377
Yes    133817
Name: count, dtype: int64

In [219]:
train["MonthlyCharges"].value_counts()

MonthlyCharges
20.05     7436
19.95     5718
19.70     5705
20.00     5493
19.85     5114
          ...
28.20        1
37.15        1
18.45        1
112.05       1
46.15        1
Name: count, Length: 1921, dtype: int64

In [220]:
train["PaymentMethod"].value_counts()

PaymentMethod
Electronic check             215372
Credit card (automatic)      133705
Mailed check                 123757
Bank transfer (automatic)    121360
Name: count, dtype: int64

In [221]:
train["PaperlessBilling"].value_counts()

PaperlessBilling
Yes    365579
No     228615
Name: count, dtype: int64

In [222]:
train["Contract"].value_counts()

Contract
Month-to-month    298918
Two year          186943
One year          108333
Name: count, dtype: int64

In [223]:
train["StreamingMovies"].value_counts()

StreamingMovies
Yes                    241435
No                     212032
No internet service    140727
Name: count, dtype: int64

In [224]:
train["StreamingTV"].value_counts()

StreamingTV
Yes                    240301
No                     213166
No internet service    140727
Name: count, dtype: int64

In [225]:
train["TechSupport"].value_counts()

TechSupport
No                     288571
Yes                    164896
No internet service    140727
Name: count, dtype: int64

In [226]:
train["DeviceProtection"].value_counts()

DeviceProtection
No                     247377
Yes                    206090
No internet service    140727
Name: count, dtype: int64

In [227]:
train["OnlineBackup"].value_counts()

OnlineBackup
No                     250083
Yes                    203384
No internet service    140727
Name: count, dtype: int64

In [228]:
train["OnlineSecurity"].value_counts()

OnlineSecurity
No                     289474
Yes                    163993
No internet service    140727
Name: count, dtype: int64

In [229]:
train["InternetService"].value_counts()

InternetService
Fiber optic    272386
DSL            181081
No             140727
Name: count, dtype: int64

In [230]:
train["MultipleLines"].value_counts()

MultipleLines
No                  283384
Yes                 274509
No phone service     36301
Name: count, dtype: int64

In [231]:
train["PhoneService"].value_counts()

PhoneService
Yes    557893
No      36301
Name: count, dtype: int64

In [232]:
train["tenure"].value_counts()

tenure
72    56411
1     29182
71    20763
2     16766
3     13478
      ...
40     4203
21     3862
44     3496
39     3396
36     2562
Name: count, Length: 72, dtype: int64

In [233]:
train["Dependents"].value_counts()

Dependents
No     414362
Yes    179832
Name: count, dtype: int64

In [234]:
train["Partner"].value_counts()

Partner
Yes    309554
No     284640
Name: count, dtype: int64

In [235]:
train["gender"].value_counts()

gender
Female    298738
Male      295456
Name: count, dtype: int64

In [236]:
train["SeniorCitizen"].value_counts()

SeniorCitizen
0    526395
1     67799
Name: count, dtype: int64

In [ ]:
train["Churn"].dtype
train["Churn"]= train["Churn"].map({"Yes":1, "No":0})

In [238]:
cat= {"Electronic check":1, "Credit card (automatic)": 2, "Mailed check":3, "Bank transfer (automatic)":4}

train["PaymentMethod"] = train["PaymentMethod"].map(cat)
test["PaymentMethod"] = test["PaymentMethod"].map(cat)

In [239]:
train["PaperlessBilling"].value_counts()

PaperlessBilling
Yes    365579
No     228615
Name: count, dtype: int64

In [240]:
cat = {"Yes":1, "No":0}
train["PaperlessBilling"] = train["PaperlessBilling"].map(cat)
test["PaperlessBilling"] = test["PaperlessBilling"].map(cat)

In [241]:
train["Contract"].value_counts()

Contract
Month-to-month    298918
Two year          186943
One year          108333
Name: count, dtype: int64

In [242]:
cat = {"Month-to-month":0, "One year": 1, "Two year":2}
train["Contract"] = train["Contract"].map(cat)
test["Contract"] = test["Contract"].map(cat)

In [243]:
train["StreamingMovies"].value_counts()

StreamingMovies
Yes                    241435
No                     212032
No internet service    140727
Name: count, dtype: int64

In [244]:
cat = {"Yes":1, "No":0, "No internet service": 2}
train["StreamingMovies"] = train["StreamingMovies"].map(cat)
test["StreamingMovies"] = test["StreamingMovies"].map(cat)

In [245]:
train["StreamingTV"].value_counts()

StreamingTV
Yes                    240301
No                     213166
No internet service    140727
Name: count, dtype: int64

In [246]:
cat = {"Yes":1, "No":0, "No internet service": 2}
train["StreamingTV"] = train["StreamingTV"].map(cat)
test["StreamingTV"] = test["StreamingTV"].map(cat)

In [247]:
train["TechSupport"].value_counts()

TechSupport
No                     288571
Yes                    164896
No internet service    140727
Name: count, dtype: int64

In [248]:
cat = {"Yes":1, "No":0, "No internet service": 2}
train["TechSupport"] = train["TechSupport"].map(cat)
test["TechSupport"] = test["TechSupport"].map(cat)

In [249]:
train["DeviceProtection"].value_counts()

DeviceProtection
No                     247377
Yes                    206090
No internet service    140727
Name: count, dtype: int64

In [250]:
cat = {"Yes":1, "No":0, "No internet service": 2}
train["DeviceProtection"] = train["DeviceProtection"].map(cat)
test["DeviceProtection"] = test["DeviceProtection"].map(cat)

In [251]:
train["OnlineBackup"].value_counts()

OnlineBackup
No                     250083
Yes                    203384
No internet service    140727
Name: count, dtype: int64

In [252]:
cat = {"Yes":1, "No":0, "No internet service": 2}
train["OnlineBackup"] = train["OnlineBackup"].map(cat)
test["OnlineBackup"] = test["OnlineBackup"].map(cat)

In [253]:
train["OnlineSecurity"].value_counts()

OnlineSecurity
No                     289474
Yes                    163993
No internet service    140727
Name: count, dtype: int64

In [254]:
cat = {"Yes":1, "No":0, "No internet service": 2}
train["OnlineSecurity"] = train["OnlineSecurity"].map(cat)
test["OnlineSecurity"] = test["OnlineSecurity"].map(cat)

In [255]:
train["InternetService"].value_counts()

InternetService
Fiber optic    272386
DSL            181081
No             140727
Name: count, dtype: int64

In [256]:
cat = {"Fiber optic":1, "No":0, "DSL": 2}
train["InternetService"] = train["InternetService"].map(cat)
test["InternetService"] = test["InternetService"].map(cat)

In [257]:
train["MultipleLines"].value_counts()

MultipleLines
No                  283384
Yes                 274509
No phone service     36301
Name: count, dtype: int64

In [258]:
cat = {"Yes":1, "No":0, "No phone service": 2}
train["MultipleLines"] = train["MultipleLines"].map(cat)
test["MultipleLines"] = test["MultipleLines"].map(cat)

In [259]:
train["PhoneService"].value_counts()

PhoneService
Yes    557893
No      36301
Name: count, dtype: int64

In [260]:
cat = {"Yes":1, "No":0}
train["PhoneService"] = train["PhoneService"].map(cat)
test["PhoneService"] = test["PhoneService"].map(cat)

In [261]:
train["Dependents"].value_counts()

Dependents
No     414362
Yes    179832
Name: count, dtype: int64

In [262]:
cat = {"Yes":1, "No":0}
train["Dependents"] = train["Dependents"].map(cat)
test["Dependents"] = test["Dependents"].map(cat)

In [263]:
train["Partner"].value_counts()

Partner
Yes    309554
No     284640
Name: count, dtype: int64

In [264]:
cat = {"Yes":1, "No":0}
train["Partner"] = train["Partner"].map(cat)
test["Partner"] = test["Partner"].map(cat)

In [265]:
train["gender"].value_counts()

gender
Female    298738
Male      295456
Name: count, dtype: int64

In [266]:
cat = {"Female":1, "Male":0}
train["gender"] = train["gender"].map(cat)
test["gender"] = test["gender"].map(cat)

In [267]:
train.drop("id", axis=1, inplace=True)
test.drop("id", axis=1, inplace=True)

In [268]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   gender            594194 non-null  int64
 1   SeniorCitizen     594194 non-null  int64
 2   Partner           594194 non-null  int64
 3   Dependents        594194 non-null  int64
 4   tenure            594194 non-null  int64
 5   PhoneService      594194 non-null  int64
 6   MultipleLines     594194 non-null  int64
 7   InternetService   594194 non-null  int64
 8   OnlineSecurity    594194 non-null  int64
 9   OnlineBackup      594194 non-null  int64
 10  DeviceProtection  594194 non-null  int64
 11  TechSupport       594194 non-null  int64
 12  StreamingTV       594194 non-null  int64
 13  StreamingMovies   594194 non-null  int64
 14  Contract          594194 non-null  int64
 15  PaperlessBilling  594194 non-null  int64
 16  PaymentMethod     594194 non-null  int64
 17  MonthlyCharges    594194 non-null  float64
 18  TotalCharges      594194 non-null  float64
 19  Churn             594194 non-null  int64
dtypes: float64(2), int64(18)
memory usage: 90.7 MB

In [269]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 254655 entries, 0 to 254654
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   gender            254655 non-null  int64
 1   SeniorCitizen     254655 non-null  int64
 2   Partner           254655 non-null  int64
 3   Dependents        254655 non-null  int64
 4   tenure            254655 non-null  int64
 5   PhoneService      254655 non-null  int64
 6   MultipleLines     254655 non-null  int64
 7   InternetService   254655 non-null  int64
 8   OnlineSecurity    254655 non-null  int64
 9   OnlineBackup      254655 non-null  int64
 10  DeviceProtection  254655 non-null  int64
 11  TechSupport       254655 non-null  int64
 12  StreamingTV       254655 non-null  int64
 13  StreamingMovies   254655 non-null  int64
 14  Contract          254655 non-null  int64
 15  PaperlessBilling  254655 non-null  int64
 16  PaymentMethod     254655 non-null  int64
 17  MonthlyCharges    254655 non-null  float64
 18  TotalCharges      254655 non-null  float64
dtypes: float64(2), int64(17)
memory usage: 36.9 MB

In [270]:
train.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [271]:
train.describe()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
count,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000
mean,0.502762,0.114102,0.520965,0.302649,36.577258,0.938907,0.584171,1.067914,0.749666,0.815959,0.820513,0.751186,0.878089,0.879997,0.811551,0.615252,2.254302,65.866223,2494.377057,0.225208
std,0.499993,0.317936,0.499561,0.459405,25.061922,0.239501,0.604236,0.732786,0.813229,0.789838,0.788001,0.812761,0.762052,0.761102,0.884403,0.486536,1.150236,31.067444,2353.916710,0.417719
min,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.250000,18.800000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,12.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,29.900000,639.650000,0.000000
50%,1.000000,0.000000,1.000000,0.000000,35.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,2.000000,74.100000,1433.650000,0.000000
75%,1.000000,0.000000,1.000000,1.000000,62.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,3.000000,90.800000,4263.800000,0.000000
max,1.000000,1.000000,1.000000,1.000000,72.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,4.000000,118.750000,8684.800000,1.000000